// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cargo.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace KPS {

namespace {

const ::google::protobuf::Descriptor* mp_cargo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  mp_cargo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cargo_2eproto() {
  protobuf_AddDesc_cargo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cargo.proto");
  GOOGLE_CHECK(file != NULL);
  mp_cargo_descriptor_ = file->message_type(0);
  static const int mp_cargo_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mp_cargo, base_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mp_cargo, cargo_type_),
  };
  mp_cargo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      mp_cargo_descriptor_,
      mp_cargo::default_instance_,
      mp_cargo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mp_cargo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(mp_cargo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(mp_cargo));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cargo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    mp_cargo_descriptor_, &mp_cargo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cargo_2eproto() {
  delete mp_cargo::default_instance_;
  delete mp_cargo_reflection_;
}

void protobuf_AddDesc_cargo_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::KPS::protobuf_AddDesc_base_2eproto();
  ::KPS::protobuf_AddDesc_cargo_5ftype_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013cargo.proto\022\003KPS\032\nbase.proto\032\020cargo_ty"
    "pe.proto\"S\n\010mp_cargo\022\037\n\004base\030\001 \002(\0132\021.KPS"
    ".mp_item_base\022&\n\ncargo_type\030\002 \002(\0132\022.KPS."
    "mp_cargo_type", 133);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cargo.proto", &protobuf_RegisterTypes);
  mp_cargo::default_instance_ = new mp_cargo();
  mp_cargo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cargo_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cargo_2eproto {
  StaticDescriptorInitializer_cargo_2eproto() {
    protobuf_AddDesc_cargo_2eproto();
  }
} static_descriptor_initializer_cargo_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int mp_cargo::kBaseFieldNumber;
const int mp_cargo::kCargoTypeFieldNumber;
#endif  // !_MSC_VER

mp_cargo::mp_cargo()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void mp_cargo::InitAsDefaultInstance() {
  base_ = const_cast< ::KPS::mp_item_base*>(&::KPS::mp_item_base::default_instance());
  cargo_type_ = const_cast< ::KPS::mp_cargo_type*>(&::KPS::mp_cargo_type::default_instance());
}

mp_cargo::mp_cargo(const mp_cargo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void mp_cargo::SharedCtor() {
  _cached_size_ = 0;
  base_ = NULL;
  cargo_type_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

mp_cargo::~mp_cargo() {
  SharedDtor();
}

void mp_cargo::SharedDtor() {
  if (this != default_instance_) {
    delete base_;
    delete cargo_type_;
  }
}

void mp_cargo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* mp_cargo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return mp_cargo_descriptor_;
}

const mp_cargo& mp_cargo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cargo_2eproto();  return *default_instance_;
}

mp_cargo* mp_cargo::default_instance_ = NULL;

mp_cargo* mp_cargo::New() const {
  return new mp_cargo;
}

void mp_cargo::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (base_ != NULL) base_->::KPS::mp_item_base::Clear();
    }
    if (_has_bit(1)) {
      if (cargo_type_ != NULL) cargo_type_->::KPS::mp_cargo_type::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool mp_cargo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .KPS.mp_item_base base = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_base()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_cargo_type;
        break;
      }
      
      // required .KPS.mp_cargo_type cargo_type = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_cargo_type:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_cargo_type()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void mp_cargo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .KPS.mp_item_base base = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->base(), output);
  }
  
  // required .KPS.mp_cargo_type cargo_type = 2;
  if (_has_bit(1)) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->cargo_type(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* mp_cargo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .KPS.mp_item_base base = 1;
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->base(), target);
  }
  
  // required .KPS.mp_cargo_type cargo_type = 2;
  if (_has_bit(1)) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->cargo_type(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int mp_cargo::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .KPS.mp_item_base base = 1;
    if (has_base()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->base());
    }
    
    // required .KPS.mp_cargo_type cargo_type = 2;
    if (has_cargo_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->cargo_type());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void mp_cargo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const mp_cargo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const mp_cargo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void mp_cargo::MergeFrom(const mp_cargo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      mutable_base()->::KPS::mp_item_base::MergeFrom(from.base());
    }
    if (from._has_bit(1)) {
      mutable_cargo_type()->::KPS::mp_cargo_type::MergeFrom(from.cargo_type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void mp_cargo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void mp_cargo::CopyFrom(const mp_cargo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool mp_cargo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  if (has_base()) {
    if (!this->base().IsInitialized()) return false;
  }
  if (has_cargo_type()) {
    if (!this->cargo_type().IsInitialized()) return false;
  }
  return true;
}

void mp_cargo::Swap(mp_cargo* other) {
  if (other != this) {
    std::swap(base_, other->base_);
    std::swap(cargo_type_, other->cargo_type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata mp_cargo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = mp_cargo_descriptor_;
  metadata.reflection = mp_cargo_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace KPS

// @@protoc_insertion_point(global_scope)
