// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "consumer.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace KPS {

namespace {

const ::google::protobuf::Descriptor* s_consumer_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  s_consumer_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_consumer_2eproto() {
  protobuf_AddDesc_consumer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "consumer.proto");
  GOOGLE_CHECK(file != NULL);
  s_consumer_descriptor_ = file->message_type(0);
  static const int s_consumer_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s_consumer, base_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s_consumer, schedule_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s_consumer, status_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s_consumer, processer_uuid_),
  };
  s_consumer_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      s_consumer_descriptor_,
      s_consumer::default_instance_,
      s_consumer_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s_consumer, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(s_consumer, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(s_consumer));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_consumer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    s_consumer_descriptor_, &s_consumer::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_consumer_2eproto() {
  delete s_consumer::default_instance_;
  delete s_consumer_reflection_;
}

void protobuf_AddDesc_consumer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::KPS::protobuf_AddDesc_base_2eproto();
  ::KPS::protobuf_AddDesc_cargo_2eproto();
  ::KPS::protobuf_AddDesc_pallet_2eproto();
  ::KPS::protobuf_AddDesc_cargo_5ftype_2eproto();
  ::KPS::protobuf_AddDesc_pallet_5ftype_2eproto();
  ::KPS::protobuf_AddDesc_lab_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016consumer.proto\022\003KPS\032\nbase.proto\032\013cargo"
    ".proto\032\014pallet.proto\032\020cargo_type.proto\032\021"
    "pallet_type.proto\032\tlab.proto\"y\n\ns_consum"
    "er\022\037\n\004base\030\001 \002(\0132\021.KPS.mp_item_base\022\"\n\010s"
    "chedule\030\002 \003(\0132\020.KPS.mp_schedule\022\016\n\006statu"
    "s\030\003 \002(\r\022\026\n\016processer_uuid\030\004 \001(\t", 231);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "consumer.proto", &protobuf_RegisterTypes);
  s_consumer::default_instance_ = new s_consumer();
  s_consumer::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_consumer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_consumer_2eproto {
  StaticDescriptorInitializer_consumer_2eproto() {
    protobuf_AddDesc_consumer_2eproto();
  }
} static_descriptor_initializer_consumer_2eproto_;


// ===================================================================

const ::std::string s_consumer::_default_processer_uuid_;
#ifndef _MSC_VER
const int s_consumer::kBaseFieldNumber;
const int s_consumer::kScheduleFieldNumber;
const int s_consumer::kStatusFieldNumber;
const int s_consumer::kProcesserUuidFieldNumber;
#endif  // !_MSC_VER

s_consumer::s_consumer()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void s_consumer::InitAsDefaultInstance() {
  base_ = const_cast< ::KPS::mp_item_base*>(&::KPS::mp_item_base::default_instance());
}

s_consumer::s_consumer(const s_consumer& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void s_consumer::SharedCtor() {
  _cached_size_ = 0;
  base_ = NULL;
  status_ = 0u;
  processer_uuid_ = const_cast< ::std::string*>(&_default_processer_uuid_);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

s_consumer::~s_consumer() {
  SharedDtor();
}

void s_consumer::SharedDtor() {
  if (processer_uuid_ != &_default_processer_uuid_) {
    delete processer_uuid_;
  }
  if (this != default_instance_) {
    delete base_;
  }
}

void s_consumer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* s_consumer::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return s_consumer_descriptor_;
}

const s_consumer& s_consumer::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_consumer_2eproto();  return *default_instance_;
}

s_consumer* s_consumer::default_instance_ = NULL;

s_consumer* s_consumer::New() const {
  return new s_consumer;
}

void s_consumer::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (_has_bit(0)) {
      if (base_ != NULL) base_->::KPS::mp_item_base::Clear();
    }
    status_ = 0u;
    if (_has_bit(3)) {
      if (processer_uuid_ != &_default_processer_uuid_) {
        processer_uuid_->clear();
      }
    }
  }
  schedule_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool s_consumer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .KPS.mp_item_base base = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_base()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_schedule;
        break;
      }
      
      // repeated .KPS.mp_schedule schedule = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_schedule:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_schedule()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_schedule;
        if (input->ExpectTag(24)) goto parse_status;
        break;
      }
      
      // required uint32 status = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_status:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &status_)));
          _set_bit(2);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(34)) goto parse_processer_uuid;
        break;
      }
      
      // optional string processer_uuid = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_processer_uuid:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_processer_uuid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->processer_uuid().data(), this->processer_uuid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void s_consumer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .KPS.mp_item_base base = 1;
  if (_has_bit(0)) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->base(), output);
  }
  
  // repeated .KPS.mp_schedule schedule = 2;
  for (int i = 0; i < this->schedule_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->schedule(i), output);
  }
  
  // required uint32 status = 3;
  if (_has_bit(2)) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->status(), output);
  }
  
  // optional string processer_uuid = 4;
  if (_has_bit(3)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->processer_uuid().data(), this->processer_uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->processer_uuid(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* s_consumer::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .KPS.mp_item_base base = 1;
  if (_has_bit(0)) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->base(), target);
  }
  
  // repeated .KPS.mp_schedule schedule = 2;
  for (int i = 0; i < this->schedule_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->schedule(i), target);
  }
  
  // required uint32 status = 3;
  if (_has_bit(2)) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->status(), target);
  }
  
  // optional string processer_uuid = 4;
  if (_has_bit(3)) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->processer_uuid().data(), this->processer_uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->processer_uuid(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int s_consumer::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .KPS.mp_item_base base = 1;
    if (has_base()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->base());
    }
    
    // required uint32 status = 3;
    if (has_status()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->status());
    }
    
    // optional string processer_uuid = 4;
    if (has_processer_uuid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->processer_uuid());
    }
    
  }
  // repeated .KPS.mp_schedule schedule = 2;
  total_size += 1 * this->schedule_size();
  for (int i = 0; i < this->schedule_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->schedule(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void s_consumer::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const s_consumer* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const s_consumer*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void s_consumer::MergeFrom(const s_consumer& from) {
  GOOGLE_CHECK_NE(&from, this);
  schedule_.MergeFrom(from.schedule_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from._has_bit(0)) {
      mutable_base()->::KPS::mp_item_base::MergeFrom(from.base());
    }
    if (from._has_bit(2)) {
      set_status(from.status());
    }
    if (from._has_bit(3)) {
      set_processer_uuid(from.processer_uuid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void s_consumer::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void s_consumer::CopyFrom(const s_consumer& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool s_consumer::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000005) != 0x00000005) return false;
  
  if (has_base()) {
    if (!this->base().IsInitialized()) return false;
  }
  for (int i = 0; i < schedule_size(); i++) {
    if (!this->schedule(i).IsInitialized()) return false;
  }
  return true;
}

void s_consumer::Swap(s_consumer* other) {
  if (other != this) {
    std::swap(base_, other->base_);
    schedule_.Swap(&other->schedule_);
    std::swap(status_, other->status_);
    std::swap(processer_uuid_, other->processer_uuid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata s_consumer::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = s_consumer_descriptor_;
  metadata.reflection = s_consumer_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace KPS

// @@protoc_insertion_point(global_scope)
