// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conf_ref_pos.proto

#ifndef PROTOBUF_conf_5fref_5fpos_2eproto__INCLUDED
#define PROTOBUF_conf_5fref_5fpos_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "base.pb.h"
// @@protoc_insertion_point(includes)

namespace KPS {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_conf_5fref_5fpos_2eproto();
void protobuf_AssignDesc_conf_5fref_5fpos_2eproto();
void protobuf_ShutdownFile_conf_5fref_5fpos_2eproto();

class mp_conf_ref_pos;

// ===================================================================

class mp_conf_ref_pos : public ::google::protobuf::Message {
 public:
  mp_conf_ref_pos();
  virtual ~mp_conf_ref_pos();
  
  mp_conf_ref_pos(const mp_conf_ref_pos& from);
  
  inline mp_conf_ref_pos& operator=(const mp_conf_ref_pos& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const mp_conf_ref_pos& default_instance();
  
  void Swap(mp_conf_ref_pos* other);
  
  // implements Message ----------------------------------------------
  
  mp_conf_ref_pos* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const mp_conf_ref_pos& from);
  void MergeFrom(const mp_conf_ref_pos& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required bool b_conf = 1;
  inline bool has_b_conf() const;
  inline void clear_b_conf();
  static const int kBConfFieldNumber = 1;
  inline bool b_conf() const;
  inline void set_b_conf(bool value);
  
  // required float confidence = 2;
  inline bool has_confidence() const;
  inline void clear_confidence();
  static const int kConfidenceFieldNumber = 2;
  inline float confidence() const;
  inline void set_confidence(float value);
  
  // required .KPS.mp_pos_data ref_pos = 3;
  inline bool has_ref_pos() const;
  inline void clear_ref_pos();
  static const int kRefPosFieldNumber = 3;
  inline const ::KPS::mp_pos_data& ref_pos() const;
  inline ::KPS::mp_pos_data* mutable_ref_pos();
  
  // @@protoc_insertion_point(class_scope:KPS.mp_conf_ref_pos)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  bool b_conf_;
  float confidence_;
  ::KPS::mp_pos_data* ref_pos_;
  friend void  protobuf_AddDesc_conf_5fref_5fpos_2eproto();
  friend void protobuf_AssignDesc_conf_5fref_5fpos_2eproto();
  friend void protobuf_ShutdownFile_conf_5fref_5fpos_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static mp_conf_ref_pos* default_instance_;
};
// ===================================================================


// ===================================================================

// mp_conf_ref_pos

// required bool b_conf = 1;
inline bool mp_conf_ref_pos::has_b_conf() const {
  return _has_bit(0);
}
inline void mp_conf_ref_pos::clear_b_conf() {
  b_conf_ = false;
  _clear_bit(0);
}
inline bool mp_conf_ref_pos::b_conf() const {
  return b_conf_;
}
inline void mp_conf_ref_pos::set_b_conf(bool value) {
  _set_bit(0);
  b_conf_ = value;
}

// required float confidence = 2;
inline bool mp_conf_ref_pos::has_confidence() const {
  return _has_bit(1);
}
inline void mp_conf_ref_pos::clear_confidence() {
  confidence_ = 0;
  _clear_bit(1);
}
inline float mp_conf_ref_pos::confidence() const {
  return confidence_;
}
inline void mp_conf_ref_pos::set_confidence(float value) {
  _set_bit(1);
  confidence_ = value;
}

// required .KPS.mp_pos_data ref_pos = 3;
inline bool mp_conf_ref_pos::has_ref_pos() const {
  return _has_bit(2);
}
inline void mp_conf_ref_pos::clear_ref_pos() {
  if (ref_pos_ != NULL) ref_pos_->::KPS::mp_pos_data::Clear();
  _clear_bit(2);
}
inline const ::KPS::mp_pos_data& mp_conf_ref_pos::ref_pos() const {
  return ref_pos_ != NULL ? *ref_pos_ : *default_instance_->ref_pos_;
}
inline ::KPS::mp_pos_data* mp_conf_ref_pos::mutable_ref_pos() {
  _set_bit(2);
  if (ref_pos_ == NULL) ref_pos_ = new ::KPS::mp_pos_data;
  return ref_pos_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace KPS

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_conf_5fref_5fpos_2eproto__INCLUDED
