#ifndef _KPS_ACTION_MENU_DEFINE_MSG_H_
#define _KPS_ACTION_MENU_DEFINE_MSG_H_

#define MENU_USER_ROOT "root"
#define MENU_USER_CLIENT "client"

#define MENU_ACT_GP_MAP      "map_menu"
#define MENU_ACT_GP_GMAPPING "gmappping_menu"
#define MENU_ACT_GP_LOC      "loc_menu"
#define MENU_ACT_GP_REF      "ref_menu"
#define MENU_ACT_GP_REFBAG   "refbag_menu"
#define MENU_ACT_GP_BAG      "bag_menu"
#define MENU_ACT_GP_MOVE     "move_menu"
#define MENU_ACT_GP_TOOLS    "tools_menu"
#define MENU_ACT_PRO_FILE    "pro_file_menu"
#define MENU_ACT_PRO_TOOLS   "pro_tools_menu"
#define MENU_ACT_PRO_TOPOL   "topological_menu"
#define MENU_ACT_PRO_ROLE    "role_menu"
#define MENU_ACT_PRO_SINGLE  "single_menu"

#define MENU_ACT_OPEN_MAP "open_map"
#define MENU_ACT_UPLOAD_MAP "upload_map"
#define MENU_ACT_DOWNLOAD_MAP "download_map"
#define MENU_ACT_DOWNLOAD_MAP_FILE "download_map_file"
#define MENU_ACT_SAVEMAP "save_map"
#define MENU_ACT_SAVE_ONBOARD_MAP "save_onboard_map"
#define MENU_ACT_SET_ONBOARD_MAP "set_onboard_map"

#define MENU_ACT_GP_LOG_BAGIN    "log_begin"
#define MENU_ACT_GP_LOG_END      "log_end"
#define MENU_ACT_GP_UPLOAD_BAG   "upload_bag"
#define MENU_ACT_GP_BAG_GMAPPING "bag_gmapping"
#define MENU_ACT_GP_BAG_CLEARBG  "clear_bag"

#define MENU_ACT_SHOW_LASER     "show_laser"
#define MENU_ACT_SHOW_PARTICLES "show_particles"
#define MENU_ACT_LOCATE         "locate"
#define MENU_ACT_AUTO_LOCATE    "auto_locate"

#define MENU_ACT_MV_CCW    "move_ccw"
#define MENU_ACT_MV_CW     "move_cw"
#define MENU_ACT_MV_FRONT  "move_front"
#define MENU_ACT_MV_BACK   "move_back"
#define MENU_ACT_MV_STOP   "move_stop"
#define MENU_ACT_MV_LEFT   "move_left"
#define MENU_ACT_MV_RIGHT  "move_right"
#define MENU_ACT_MV_ORI    "move_ori"
#define MENU_ACT_MV_SHOW   "move_show"

#define MENU_ACT_TOOLS_SEARCH_PATH    "tools_search_path"
#define MENU_ACT_TOOLS_SHOW_EX_REF    "tools_show_ex_reflector"
#define MENU_ACT_TOOLS_DYNAMIC_LOC    "tools_dynamic_loc"
#define MENU_ACT_TOOLS_SCAN_MATCH     "tools_scan_match"
#define MENU_ACT_TOOLS_ADD_QRCODE     "tools_add_qrcode"
#define MENU_ACT_TOOLS_EXP_QRCODE     "tools_exp_qrcode"
#define MENU_ACT_TOOLS_IMP_QRCODE     "tools_imp_qrcode"

#define MENU_ACT_REFLECTOR_OPEN       "open_reflector"
#define MENU_ACT_REFLECTOR_SAVE       "save_reflector"
#define MENU_ACT_REFLECTOR_UPLOAD     "upload_reflector"
#define MENU_ACT_REFLECTOR_DOWNLOAD   "download_reflector"
#define MENU_ACT_REFLECTOR_ADD        "add_reflector"
#define MENU_ACT_REFLECTOR_DEL        "del_reflector"
#define MENU_ACT_REFLECTOR_SELECT     "sel_reflector"

#define MENU_ACT_REFBAG_LOGEX_BEGIN   "logex_begin"
#define MENU_ACT_REFBAG_LOGEX_STOP    "logex_stop"
#define MENU_ACT_REFBAG_LOGEX_UPLOAD  "logex_upload"
#define MENU_ACT_REFBAG_LOGEX_MAPPING "logex_mapping"
#define MENU_ACT_REFBAG_LOGEX_GMAP    "logex_gmap"
#define MENU_ACT_REFBAG_LOGEX_MODIFY  "logex_modify"
#define MENU_ACT_REFBAG_LOGEX_G2O     "logex_g2o"
#define MENU_ACT_REFBAG_LOGEX_CLEARBG "clear_bag"

#define MENU_ACT_BAG_CLEARBG           "clear_bag"
#define MENU_ACT_BAG_UPLOAD            "upload_bag"
#define MENU_ACT_BAG_PLABBACK          "playback_bag"
#define MENU_ACT_BAG_PLABBACK_EX       "playback_bag_ex"
#define MENU_ACT_BAG_DYNAMIC_FRAME     "dynamic_key_frame"

#define MENU_ACT_PROFILE_OPEN          "open_project"
#define MENU_ACT_PROFILE_SAVE          "save_project"
#define MENU_ACT_PROFILE_UPLOAD        "upload_project"
#define MENU_ACT_PROFILE_DOWNLOAD      "download_project"
#define MENU_ACT_PROFILE_SET_ONBOARD   "set_onboard_project"

#define MENU_ACT_PROTOOLS_SELECT       "select_item"
#define MENU_ACT_PROTOOLS_ALIGN        "align_item"
#define MENU_ACT_PROTOOLS_DEL          "del_roles_project"

#define MENU_ACT_PROTOPO_NODE          "node_project"
#define MENU_ACT_PROTOPO_EDGE          "edge_project"
#define MENU_ACT_PROTOPO_RAND_EDGE     "rand_edge_project"
#define MENU_ACT_PROTOPO_RANGE         "range_project"
#define MENU_ACT_PROTOPO_RECT          "rect_project"

#define MENU_ACT_PROSINGLE_WANDER      "wander_single"
#define MENU_ACT_PROSINGLE_AUTO_COV    "auto_cov_single"

#define MENU_ACT_PROROLE_PRODUCER      "producer"
#define MENU_ACT_PROROLE_CONSUMER      "consumer"
#define MENU_ACT_PROROLE_PROCESSER     "processer"
#define MENU_ACT_PROROLE_STORAGE       "storage"
#define MENU_ACT_PROROLE_CHARGE        "charge"


#endif // _KPS_ACTION_MENU_DEFINE_MSG_H_
