#ifndef _TASK_ERROR_CODE_KYOSHO_20150906_
#define _TASK_ERROR_CODE_KYOSHO_20150906_

#define TASK_ERR_FORCE_COMPLETE 0
#define TASK_ERR_PARA_LEN_ERROR 1
#define TASK_ERR_PATH_RUN_PARA_ERROR 2
#define TASK_ERR_PATH_RUN_SET_ERROR 3
#define TASK_ERR_PATH_RUN_CHECK_ERROR 4
#define TASK_ERR_OPEN_CTL_CHECK_ERROR 5
#define TASK_ERR_OPEN_CTL_SETSPEED_ERROR 6
#define TASK_ERR_FORK_SET_ERROR 7
#define TASK_ERR_FORK_CHECK_ERROR 8
#endif//_TASK_ERROR_CODE_KYOSHO_20150906_
