// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GErrorCode.proto

#ifndef PROTOBUF_GErrorCode_2eproto__INCLUDED
#define PROTOBUF_GErrorCode_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_GErrorCode_2eproto();
void protobuf_AssignDesc_GErrorCode_2eproto();
void protobuf_ShutdownFile_GErrorCode_2eproto();

class GErrorCode;

// ===================================================================

class GErrorCode : public ::google::protobuf::Message {
 public:
  GErrorCode();
  virtual ~GErrorCode();
  
  GErrorCode(const GErrorCode& from);
  
  inline GErrorCode& operator=(const GErrorCode& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GErrorCode& default_instance();
  
  void Swap(GErrorCode* other);
  
  // implements Message ----------------------------------------------
  
  GErrorCode* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GErrorCode& from);
  void MergeFrom(const GErrorCode& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required bytes process_name = 1;
  inline bool has_process_name() const;
  inline void clear_process_name();
  static const int kProcessNameFieldNumber = 1;
  inline const ::std::string& process_name() const;
  inline void set_process_name(const ::std::string& value);
  inline void set_process_name(const char* value);
  inline void set_process_name(const void* value, size_t size);
  inline ::std::string* mutable_process_name();
  
  // required int32 process_status = 2;
  inline bool has_process_status() const;
  inline void clear_process_status();
  static const int kProcessStatusFieldNumber = 2;
  inline ::google::protobuf::int32 process_status() const;
  inline void set_process_status(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:GErrorCode)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* process_name_;
  static const ::std::string _default_process_name_;
  ::google::protobuf::int32 process_status_;
  friend void  protobuf_AddDesc_GErrorCode_2eproto();
  friend void protobuf_AssignDesc_GErrorCode_2eproto();
  friend void protobuf_ShutdownFile_GErrorCode_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GErrorCode* default_instance_;
};
// ===================================================================


// ===================================================================

// GErrorCode

// required bytes process_name = 1;
inline bool GErrorCode::has_process_name() const {
  return _has_bit(0);
}
inline void GErrorCode::clear_process_name() {
  if (process_name_ != &_default_process_name_) {
    process_name_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& GErrorCode::process_name() const {
  return *process_name_;
}
inline void GErrorCode::set_process_name(const ::std::string& value) {
  _set_bit(0);
  if (process_name_ == &_default_process_name_) {
    process_name_ = new ::std::string;
  }
  process_name_->assign(value);
}
inline void GErrorCode::set_process_name(const char* value) {
  _set_bit(0);
  if (process_name_ == &_default_process_name_) {
    process_name_ = new ::std::string;
  }
  process_name_->assign(value);
}
inline void GErrorCode::set_process_name(const void* value, size_t size) {
  _set_bit(0);
  if (process_name_ == &_default_process_name_) {
    process_name_ = new ::std::string;
  }
  process_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GErrorCode::mutable_process_name() {
  _set_bit(0);
  if (process_name_ == &_default_process_name_) {
    process_name_ = new ::std::string;
  }
  return process_name_;
}

// required int32 process_status = 2;
inline bool GErrorCode::has_process_status() const {
  return _has_bit(1);
}
inline void GErrorCode::clear_process_status() {
  process_status_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 GErrorCode::process_status() const {
  return process_status_;
}
inline void GErrorCode::set_process_status(::google::protobuf::int32 value) {
  _set_bit(1);
  process_status_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GErrorCode_2eproto__INCLUDED
